name: Linux build

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Qt
      uses: jurplel/install-qt-action@v3.0.0
      with:
        version: 5.15.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |
        python build.py build appimage

    - name: Upload to GitHub
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Nunnix-Manga
        path: Nunnix-Manga-x86_64.AppImage
        if-no-files-found: error
