name: Linux build

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.3.0
      with:
        python-version: "3.10"

    - name: Install Qt5 dependencies
      run: |
        sudo apt-get install libxcb-xinerama0 libfuse2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: |
        python build.py build appimage

    - name: Upload to GitHub
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Nunnix-Manga
        path: Nunnix-Manga-x86_64.AppImage
        if-no-files-found: error
